### ISSUE TITLE
大佬有qq不

### ISSUE THREAD

**Issue by hongzhe12** [weiran1999/spider#1]
我是小白 对你的代码感兴趣 想学习
我qq 2528104776

**Comment by weiraneve** [comment]
907221539

**Comment by hongzhe12** [comment]
什么情况？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月08日 23:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [weiraneve/spider] 大佬有qq不 (#1) |

Closed #1 as completed.

**Comment by weiraneve** [comment]
> 什么情况？
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年05月08日 23:42 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [weiraneve/spider] 大佬有qq不 (#1) | Closed #1 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

怎么了🤔
